GET http://localhost:8080/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODEyOTYiLCJuYW1lIjoiNjY2Iiwid2hvIjoibWFzdGVyIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE2NjkyODg4NDV9.Vu7NxQquUZ-HXsHaEcZVXg7ak4XHTOagw_OaOr0g1ku83MCh2d7u8TLcrO4CYdczulHx0depWaEk2IUB0o855nF7rcDQ6XILO_BIODh9g1EvCexQ8_X1LT4jNrwKq5sqQ6-I5JJghux3RAjUOSYrwvwnXI8WkcTo5iTVAbEUTHpgvLtInV3ucILPy9LyaMl51suC1-DrmH1iusKYjuy12vO6YDZJNsR4U64v9-LJ5E_S1bnQv3moSEIcytsmfNN4xZ4RMQ5h05Q_bLbp8MzNtLulFkKzpWeHnFgOlORnuEhzf7dEvGVUtbKrI3EPkR5ymB6vGyRzbqKRFi_LyMDXhg